@DiveBuddyFinder_HostAddress = https://localhost:7140
POST {{DiveBuddyFinder_HostAddress}}/api/Auth/GetVerificationCode
Accept: application/json
Content-Type: application/json
"camin24268@linxues.com"
###
