INSERT INTO Location (Postcode, Suburb, State, CountryCode) VALUES
('1001', 'Sydney', 'New South Wales', 'AU'),
('1208', 'Haymarket', 'New South Wales', 'AU'),
('1209', 'Australia Square', 'New South Wales', 'AU'),
('1216', 'Grosvenor Place', 'New South Wales', 'AU'),
('1221', 'Royal Exchange', 'New South Wales', 'AU'),
('1226', 'Queen Victoria Building', 'New South Wales', 'AU'),
('1231', 'Sydney South', 'New South Wales', 'AU'),
('1300', 'Darlinghurst', 'New South Wales', 'AU'),
('1311', 'Eastern Suburbs Mc', 'New South Wales', 'AU'),
('1335', 'Potts Point', 'New South Wales', 'AU'),
('1340', 'Kings Cross', 'New South Wales', 'AU'),
('1350', 'Woollahra', 'New South Wales', 'AU'),
('1355', 'Bondi Junction', 'New South Wales', 'AU'),
('1360', 'Double Bay', 'New South Wales', 'AU'),
('1363', 'Moore Park', 'New South Wales', 'AU'),
('1401', 'Broadway', 'New South Wales', 'AU'),
('1416', 'Southern Suburbs Mc', 'New South Wales', 'AU'),
('1420', 'Strawberry Hills', 'New South Wales', 'AU'),
('1430', 'Eveleigh', 'New South Wales', 'AU'),
('1435', 'Alexandria', 'New South Wales', 'AU'),
('1440', 'Waterloo', 'New South Wales', 'AU'),
('1445', 'Rosebery', 'New South Wales', 'AU'),
('1450', 'Camperdown', 'New South Wales', 'AU'),
('1455', 'Botany', 'New South Wales', 'AU'),
('1460', 'Mascot', 'New South Wales', 'AU'),
('1465', 'Kensington', 'New South Wales', 'AU'),
('1466', 'Unsw Sydney', 'New South Wales', 'AU'),
('1470', 'Drummoyne', 'New South Wales', 'AU'),
('1475', 'Marrickville', 'New South Wales', 'AU'),
('1480', 'Kingsgrove', 'New South Wales', 'AU'),
('1481', 'Hurstville Bc', 'New South Wales', 'AU'),
('1484', 'Kingsgrove DC', 'New South Wales', 'AU'),
('1485', 'Kogarah', 'New South Wales', 'AU'),
('1490', 'Miranda', 'New South Wales', 'AU'),
('1493', 'Hurstville', 'New South Wales', 'AU'),
('1495', 'Caringbah', 'New South Wales', 'AU'),
('1499', 'Sutherland', 'New South Wales', 'AU'),
('1515', 'West Chatswood', 'New South Wales', 'AU'),
('1560', 'Northbridge', 'New South Wales', 'AU'),
('1565', 'Milsons Point', 'New South Wales', 'AU'),
('1570', 'Artarmon', 'New South Wales', 'AU'),
('1582', 'Crows Nest', 'New South Wales', 'AU'),
('1590', 'St Leonards', 'New South Wales', 'AU'),
('1595', 'Lane Cove', 'New South Wales', 'AU'),
('1602', 'Lane Cove DC', 'New South Wales', 'AU'),
('1630', 'Hornsby', 'New South Wales', 'AU'),
('1635', 'Hornsby Westfield', 'New South Wales', 'AU'),
('1639', 'Frenchs Forest', 'New South Wales', 'AU'),
('1655', 'Manly', 'New South Wales', 'AU'),
('1658', 'Mona Vale', 'New South Wales', 'AU'),
('1670', 'North Ryde Bc', 'New South Wales', 'AU'),
('1671', 'North Ryde', 'New South Wales', 'AU'),
('1675', 'Gladesville', 'New South Wales', 'AU'),
('1680', 'Ryde', 'New South Wales', 'AU'),
('1685', 'West Ryde', 'New South Wales', 'AU'),
('1690', 'Northern Suburbs Mc', 'New South Wales', 'AU'),
('1700', 'Ermington', 'New South Wales', 'AU'),
('1701', 'Rydalmere Bc', 'New South Wales', 'AU'),
('1710', 'Epping', 'New South Wales', 'AU'),
('1715', 'Pennant Hills', 'New South Wales', 'AU'),
('1730', 'Seven Hills', 'New South Wales', 'AU'),
('1740', 'Parramatta', 'New South Wales', 'AU'),
('1750', 'North Parramatta', 'New South Wales', 'AU'),
('1755', 'Baulkham Hills', 'New South Wales', 'AU'),
('1765', 'Castle Hill', 'New South Wales', 'AU'),
('1781', 'Seven Hills Mc', 'New South Wales', 'AU'),
('1790', 'St Marys', 'New South Wales', 'AU'),
('1797', 'Penrith South DC', 'New South Wales', 'AU'),
('1800', 'Ashfield', 'New South Wales', 'AU'),
('1805', 'Burwood', 'New South Wales', 'AU'),
('1811', 'Silverwater', 'New South Wales', 'AU'),
('1825', 'Lidcombe', 'New South Wales', 'AU'),
('1830', 'Granville', 'New South Wales', 'AU'),
('1835', 'Auburn', 'New South Wales', 'AU'),
('1848', 'Guildford', 'New South Wales', 'AU'),
('1851', 'Wetherill Park Dc', 'New South Wales', 'AU'),
('1860', 'Fairfield', 'New South Wales', 'AU'),
('1871', 'Liverpool', 'New South Wales', 'AU'),
('1875', 'Moorebank', 'New South Wales', 'AU'),
('1885', 'Bankstown', 'New South Wales', 'AU'),
('1890', 'Ingleburn', 'New South Wales', 'AU'),
('1891', 'Milperra', 'New South Wales', 'AU'),
('1900', 'Leightonfield Mc', 'New South Wales', 'AU'),
('2002', 'World Square', 'New South Wales', 'AU'),
('2006', 'The University Of Sydney', 'New South Wales', 'AU'),
('2008', 'Darlington', 'New South Wales', 'AU'),
('2009', 'Pyrmont', 'New South Wales', 'AU'),
('2010', 'Surry Hills', 'New South Wales', 'AU'),
('2011', 'Rushcutters Bay', 'New South Wales', 'AU'),
('2016', 'Redfern', 'New South Wales', 'AU'),
('2017', 'Zetland', 'New South Wales', 'AU'),
('2018', 'Eastlakes', 'New South Wales', 'AU'),
('2020', 'Sydney International Airport', 'New South Wales', 'AU'),
('2021', 'Centennial Park', 'New South Wales', 'AU'),
('2023', 'Bellevue Hill', 'New South Wales', 'AU'),
('2024', 'Waverley', 'New South Wales', 'AU'),
('2026', 'Tamarama', 'New South Wales', 'AU'),
('2027', 'Point Piper', 'New South Wales', 'AU'),
('2029', 'Rose Bay', 'New South Wales', 'AU'),
('2030', 'Dover Heights', 'New South Wales', 'AU'),
('2031', 'Clovelly West', 'New South Wales', 'AU'),
('2032', 'Daceyville', 'New South Wales', 'AU'),
('2034', 'South Coogee', 'New South Wales', 'AU'),
('2035', 'Maroubra', 'New South Wales', 'AU'),
('2036', 'Port Botany', 'New South Wales', 'AU'),
('2037', 'Forest Lodge', 'New South Wales', 'AU'),
('2038', 'Annandale', 'New South Wales', 'AU'),
('2039', 'Rozelle', 'New South Wales', 'AU'),
('2040', 'Leichhardt', 'New South Wales', 'AU'),
('2041', 'Balmain', 'New South Wales', 'AU'),
('2042', 'Enmore', 'New South Wales', 'AU'),
('2043', 'Erskineville', 'New South Wales', 'AU'),
('2044', 'Sydenham', 'New South Wales', 'AU'),
('2045', 'Haberfield', 'New South Wales', 'AU'),
('2046', 'Abbotsford', 'New South Wales', 'AU'),
('2048', 'Stanmore', 'New South Wales', 'AU'),
('2049', 'Petersham North', 'New South Wales', 'AU'),
('2050', 'Missenden Road', 'New South Wales', 'AU'),
('2055', 'North Sydney', 'New South Wales', 'AU'),
('2057', 'Chatswood', 'New South Wales', 'AU'),
('2060', 'Hmas Waterhen', 'New South Wales', 'AU'),
('2062', 'Cammeray', 'New South Wales', 'AU'),
('2065', 'Wollstonecraft', 'New South Wales', 'AU'),
('2066', 'Lane Cove North', 'New South Wales', 'AU'),
('2067', 'Chatswood West', 'New South Wales', 'AU'),
('2068', 'North Willoughby', 'New South Wales', 'AU'),
('2069', 'Castle Cove', 'New South Wales', 'AU'),
('2070', 'Lindfield West', 'New South Wales', 'AU'),
('2071', 'Killara', 'New South Wales', 'AU'),
('2072', 'Gordon', 'New South Wales', 'AU'),
('2073', 'Pymble', 'New South Wales', 'AU'),
('2074', 'Warrawee', 'New South Wales', 'AU'),
('2075', 'St Ives Chase', 'New South Wales', 'AU'),
('2076', 'Normanhurst', 'New South Wales', 'AU'),
('2079', 'Mount Colah', 'New South Wales', 'AU'),
('2080', 'Mount Kuring-Gai', 'New South Wales', 'AU'),
('2081', 'Berowra', 'New South Wales', 'AU'),
('2082', 'Berowra Heights', 'New South Wales', 'AU'),
('2083', 'Cheero Point', 'New South Wales', 'AU'),
('2084', 'Cottage Point', 'New South Wales', 'AU'),
('2085', 'Belrose', 'New South Wales', 'AU'),
('2086', 'Frenchs Forest East', 'New South Wales', 'AU'),
('2087', 'Killarney Heights', 'New South Wales', 'AU'),
('2088', 'Spit Junction', 'New South Wales', 'AU'),
('2089', 'Neutral Bay', 'New South Wales', 'AU'),
('2090', 'Cremorne', 'New South Wales', 'AU'),
('2091', 'Hmas Penguin', 'New South Wales', 'AU'),
('2092', 'Seaforth', 'New South Wales', 'AU'),
('2093', 'Balgowlah Heights', 'New South Wales', 'AU'),
('2094', 'Fairlight', 'New South Wales', 'AU'),
('2095', 'Manly East', 'New South Wales', 'AU'),
('2096', 'Freshwater', 'New South Wales', 'AU'),
('2097', 'Collaroy Beach', 'New South Wales', 'AU'),
('2099', 'North Curl Curl', 'New South Wales', 'AU'),
('2100', 'Allambie Heights', 'New South Wales', 'AU'),
('2101', 'Elanora Heights', 'New South Wales', 'AU'),
('2102', 'Warriewood Shopping Square', 'New South Wales', 'AU'),
('2104', 'Bayview', 'New South Wales', 'AU'),
('2105', 'Elvina Bay', 'New South Wales', 'AU'),
('2106', 'Newport Beach', 'New South Wales', 'AU'),
('2107', 'Avalon Beach', 'New South Wales', 'AU'),
('2108', 'The Basin', 'New South Wales', 'AU'),
('2109', 'Macquarie University', 'New South Wales', 'AU'),
('2110', 'Woolwich', 'New South Wales', 'AU'),
('2111', 'Henley', 'New South Wales', 'AU'),
('2112', 'Putney', 'New South Wales', 'AU'),
('2113', 'East Ryde', 'New South Wales', 'AU'),
('2114', 'Denistone', 'New South Wales', 'AU'),
('2116', 'Rydalmere', 'New South Wales', 'AU'),
('2117', 'Dundas', 'New South Wales', 'AU'),
('2118', 'Carlingford', 'New South Wales', 'AU'),
('2119', 'Cheltenham', 'New South Wales', 'AU');